from __future__ import annotations

from typing import Protocol

from src.models import Task, User


class UserRepository(Protocol):
    def add(self, user: User) -> None: ...

    def get_by_username(self, username: str) -> User | None: ...


class TaskRepository(Protocol):
    def add(self, task: Task) -> None: ...

    def get(self, task_id: str) -> Task | None: ...

    def list_by_owner(self, owner_id: str) -> list[Task]: ...

    def update(self, task: Task) -> None: ...

    def delete(self, task_id: str) -> None: ...
